name = "Sanghoon"
uuid = "da6f92b3-8aaf-4463-a33f-a174f3e9ca4d"
authors = ["Sanghoon Lee <sanghoon.lee@sauder.ubc.ca> and contributors"]
version = "0.1.0"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
